#pragma once
#include "UIBase.h" // :O auto generated by vs2022 >:)

class ResourceManager;
class Inventory;

class InventorySlots :  public UIBase
{
public:
	InventorySlots() = default;

	void Init(const ResourceManager& resourceMananger, Inventory* inventory);

	void Update(float) override {};

	void Draw(Surface& target, int2 offset) const override;

private:
	void DrawItem(Surface& target, int2 offset, ItemType item) const;

	Inventory* inventory;

	TileSheet* itemSlotIcon;
	TileSheet* itemSheet;

	Font* itemCountFont;

};

